language: python
python:
  - '3.8'

services:
  - postgresql

branches:
  only:
    - staging

before_install:
  - export DJANGO_SETTINGS_MODULE='pur_beurre.settings'
  - export DJANGO_KEY='TiXNqf0Q2byC2rxwtQPAH8CduE0t2Lt5'
  - export DB_NAME='travisdb'
  - export DB_USER='postgres'
  - export DB_PASSWORD=''
  - export DB_HOST=''
  - export DB_PORT=''

before_script:
  - pip install -r requirements.txt
  - psql -c "CREATE DATABASE travisdb;" -U postgres

script:
  - python3 manage.py test
